apiVersion: v1
kind: Service
metadata:
  name: linkedin-analyzer-service
spec:
  selector:
    app: linkedin-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
